spring:
  redis:
    hosts: localhost
    port: 6379

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url:
    username:
    password:

  mybatis:
    mapper-locations: classpath:mapper/*.xml

  jwt:
    secret: json.web.token.secret.key.test