spring:
  redis:
    hosts: localhost
    port: 6379

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/users
    username: root
    password: 1234

  mybatis:
    mapper-locations: classpath:mapper/*.xml

  jwt:
    secret: json.web.token.secret.key.test
    refresh-token-validity-in-seconds: 1209600 # 리프레시 토큰 유효시간 초 단위
    access-token-validity-in-seconds: 43200 # 액세스 토큰 유효시간 초 단위